using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GManagerial.Products.ChildForms
{
    static class ProductQueries
    {
        //delete product
        static public string DELETEPRODUCT = "DELETE FROM PRODUCTSTBL WHERE PRODUCT_ID = @PRODUCT_ID";
        static public string DELETEWAREHOUSEPRODUCT = "DELETE FROM WAREHOUSEPRODUCT WHERE PRODUCT_ID = @PRODUCT_ID";
        static public string DELETEPRODUCTSUPPLIER = "DELETE FROM PRODUCT_SUPPLIER WHERE PRODUCT_ID = @PRODUCT_ID"; //cancella tutti i fornitori abbinati
        static public string DELETEPRODUCTPRICES = "DELETE FROM SELLPRODUCTPRICES WHERE PRODUCT_ID = @PRODUCT_ID";

        static public string SEARCHPRODUCTS = "SELECT *, B.BRAND_NAME, C.CATEGORY_NAME, S.SUBCATEGORY_NAME FROM PRODUCTSTBL P JOIN CATEGORIESTBL C ON P.CATEGORY_ID = C.CATEGORY_ID JOIN SUBCATEGORYTBL S" +
                " ON P.SUBCATEGORY_ID = S.SUBCATEGORY_ID JOIN BRANDTBL B ON P.ID_BRAND = B.ID_BRAND WHERE P.PRODUCT_NAME LIKE @SEARCHVALUE OR P.DESCRIPTION LIKE @SEARCHVALUE " +
                "OR C.CATEGORY_NAME LIKE @SEARCHVALUE OR S.SUBCATEGORY_NAME LIKE @SEARCHVALUE OR B.BRAND_NAME LIKE @SEARCHVALUE";

        static public string SEARCHCATEGORIZEDPRODUCTS = "SELECT *, B.BRAND_NAME, C.CATEGORY_NAME, S.SUBCATEGORY_NAME FROM PRODUCTSTBL P JOIN CATEGORIESTBL C" +
            " ON P.CATEGORY_ID = C.CATEGORY_ID JOIN SUBCATEGORYTBL S ON P.SUBCATEGORY_ID = S.SUBCATEGORY_ID JOIN BRANDTBL B ON P.ID_BRAND = B.ID_BRAND " +
            "WHERE (P.PRODUCT_NAME LIKE @SEARCHVALUE OR P.DESCRIPTION LIKE @SEARCHVALUE) AND C.CATEGORY_NAME LIKE @CATEGORY_NAME";

        static public string SEARCHCATEGORIZEDANDSUBPRODUCTS = "SELECT *, B.BRAND_NAME, C.CATEGORY_NAME, S.SUBCATEGORY_NAME FROM PRODUCTSTBL P JOIN CATEGORIESTBL C" +
            " ON P.CATEGORY_ID = C.CATEGORY_ID JOIN SUBCATEGORYTBL S ON P.SUBCATEGORY_ID = S.SUBCATEGORY_ID JOIN BRANDTBL B ON P.ID_BRAND = B.ID_BRAND " +
            "WHERE (P.PRODUCT_NAME LIKE @SEARCHVALUE OR P.DESCRIPTION LIKE @SEARCHVALUE) AND C.CATEGORY_NAME LIKE @CATEGORY_NAME AND S.SUBCATEGORY_NAME LIKE @SUBCATEGORY_NAME";

        static public string SEARCHBRANDIZEDPRODUCTS = "SELECT *, B.BRAND_NAME, C.CATEGORY_NAME, S.SUBCATEGORY_NAME FROM PRODUCTSTBL P JOIN CATEGORIESTBL C" +
           " ON P.CATEGORY_ID = C.CATEGORY_ID JOIN SUBCATEGORYTBL S ON P.SUBCATEGORY_ID = S.SUBCATEGORY_ID JOIN BRANDTBL B ON P.ID_BRAND = B.ID_BRAND " +
           "WHERE (P.PRODUCT_NAME LIKE @SEARCHVALUE OR P.DESCRIPTION LIKE @SEARCHVALUE) AND B.BRAND_NAME LIKE @BRAND_NAME";

        static public string SEARCHCATEGORIZEDBRANDIZEDPRODUCTS = "SELECT *, B.BRAND_NAME, C.CATEGORY_NAME, S.SUBCATEGORY_NAME FROM PRODUCTSTBL P JOIN CATEGORIESTBL C" +
            " ON P.CATEGORY_ID = C.CATEGORY_ID JOIN SUBCATEGORYTBL S ON P.SUBCATEGORY_ID = S.SUBCATEGORY_ID JOIN BRANDTBL B ON P.ID_BRAND = B.ID_BRAND " +
            "WHERE (P.PRODUCT_NAME LIKE @SEARCHVALUE OR P.DESCRIPTION LIKE @SEARCHVALUE) AND C.CATEGORY_NAME LIKE @CATEGORY_NAME AND B.BRAND_NAME LIKE @BRAND_NAME";

        static public string SEARCHCATEGORIZEDANDSUBBRANDIZEDPRODUCTS = "SELECT *, B.BRAND_NAME, C.CATEGORY_NAME, S.SUBCATEGORY_NAME FROM PRODUCTSTBL P JOIN CATEGORIESTBL C" +
            " ON P.CATEGORY_ID = C.CATEGORY_ID JOIN SUBCATEGORYTBL S ON P.SUBCATEGORY_ID = S.SUBCATEGORY_ID JOIN BRANDTBL B ON P.ID_BRAND = B.ID_BRAND " +
            "WHERE (P.PRODUCT_NAME LIKE @SEARCHVALUE OR P.DESCRIPTION LIKE @SEARCHVALUE) AND C.CATEGORY_NAME LIKE @CATEGORY_NAME AND S.SUBCATEGORY_NAME LIKE @SUBCATEGORY_NAME AND B.BRAND_NAME LIKE @BRAND_NAME";

        static public string SEARCHPRODUCTSWITHSUPPLIER = @"SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.SERIAL_NUMBER, P.DESCRIPTION, P.ENERGY_CLASS, P.NOTES, P.DEPTH, P.HEIGHT, P.WEIGHT, P.WIDTH, P.POWER,
                                                            P.ENERGY_CONSUMPTION, P.MANUFACTURING_DATE, P.RESIZEDIMAGE, P.IMAGE,
                                                            B.BRAND_NAME, C.CATEGORY_NAME, SC.SUBCATEGORY_NAME, S.SUPPLIER_ID, S.SUPPLIER_NAME
                                                            FROM PRODUCTSTBL P
                                                            JOIN CATEGORIESTBL C
                                                            ON P.CATEGORY_ID = C.CATEGORY_ID 
                                                            JOIN SUBCATEGORYTBL SC
                                                            ON P.SUBCATEGORY_ID = SC.SUBCATEGORY_ID
                                                            JOIN BRANDTBL B 
                                                            ON P.ID_BRAND = B.ID_BRAND
                                                            JOIN PRODUCT_SUPPLIER PS
                                                            ON P.PRODUCT_ID = PS.PRODUCT_ID
                                                            JOIN SUPPLIERSTBL S
                                                            ON PS.SUPPLIER_ID = S.SUPPLIER_ID
                                                            WHERE (P.PRODUCT_NAME LIKE @SEARCHVALUE OR P.DESCRIPTION LIKE @SEARCHVALUE
                                                            OR C.CATEGORY_NAME LIKE @SEARCHVALUE OR SC.SUBCATEGORY_NAME LIKE @SEARCHVALUE OR B.BRAND_NAME LIKE @SEARCHVALUE)
                                                            AND S.SUPPLIER_ID = @SUPPLIER_ID";

    }
}
