using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GManagerial.Customers.models
{
    internal static class CustomerQueries
    {
        static public string SEARCHCUSTOMER = "SELECT * FROM CUSTOMERTBL WHERE CUSTOMER_ID LIKE @SEARCHVALUE OR NAME LIKE @SEARCHVALUE OR REGION LIKE @SEARCHVALUE OR PROVINCE LIKE @SEARCHVALUE" +
            " OR CITY LIKE @SEARCHVALUE";


        static public string SEARCHCUSTOMERWITHREGION = "SELECT * FROM CUSTOMERTBL WHERE (CUSTOMER_ID LIKE @SEARCHVALUE OR NAME LIKE @SEARCHVALUE) AND REGION LIKE @REGION";
        static public string SEARCHCUSTOMERWITHREGIONANDPROVINCE = "SELECT * FROM CUSTOMERTBL WHERE (CUSTOMER_ID LIKE @SEARCHVALUE OR NAME LIKE @SEARCHVALUE) AND REGION LIKE @REGION " +
            "AND PROVINCE LIKE @PROVINCE";
        static public string SEARCHCUSTOMERWITHREGIONPROVINCEANDCITY = "SELECT * FROM CUSTOMERTBL WHERE (CUSTOMER_ID LIKE @SEARCHVALUE OR NAME LIKE @SEARCHVALUE) AND REGION LIKE @REGION " +
            "AND PROVINCE LIKE @PROVINCE AND CITY LIKE @CITY";

        /*static public string SEARCHCUSTOMERWITHREGIONANDCITY = "SELECT * FROM CUSTOMERTBL WHERE (CUSTOMER_ID LIKE @SEARCHVALUE OR NAME LIKE @SEARCHVALUE) AND REGION LIKE @REGION " +
            "AND CITY LIKE @CITY";*/
    }
}
