using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GManagerial
{
    static class SupplierQueries
    {
        /*static public string GETUNSELECTEDPRODUCTSUPPLIERS = @"SELECT S.*
                             FROM SUPPLIERSTBL S
                             LEFT JOIN
                             (SELECT SUPPLIER_ID
                             FROM PRODUCT_SUPPLIER
                             WHERE PRODUCT_ID = @PRODUCT_ID)
                             PS ON S.SUPPLIER_ID = PS.SUPPLIER_ID
                             WHERE PS.SUPPLIER_ID IS NULL";

        static public string GETSELECTEDPRODUCTSUPPLIERS = "SELECT * FROM SUPPLIERSTBL S LEFT JOIN PRODUCT_SUPPLIER PS ON S.SUPPLIER_ID = PS.SUPPLIER_ID" +
            " WHERE PRODUCT_ID = @PRODUCT_ID OR S.SUPPLIER_NAME = '-'";*/

        static public string DELETEPRODUCTSUPPLIER = "DELETE FROM PRODUCT_SUPPLIER WHERE SUPPLIER_ID = @SUPPLIER_ID";

        static public string DELETESUPPLIER = "DELETE FROM SUPPLIERSTBL WHERE SUPPLIER_ID = @SUPPLIER_ID";

        static public string DELETESUPPLIERPRICES = "DELETE FROM SELLPRODUCTPRICES WHERE SUPPLIER_ID = @SUPPLIER_ID";

        static public string SEARCHSUPPLIER = "SELECT * FROM SUPPLIERSTBL WHERE SUPPLIER_ID LIKE @SEARCHVALUE OR SUPPLIER_NAME LIKE @SEARCHVALUE OR REGION LIKE @SEARCHVALUE" +
            " OR PROVINCE LIKE @SEARCHVALUE OR CITY LIKE @SEARCHVALUE";

        static public string SEARCHSUPPLIERWITHREGION = "SELECT * FROM SUPPLIERSTBL WHERE (SUPPLIER_ID LIKE @SEARCHVALUE OR SUPPLIER_NAME LIKE @SEARCHVALUE) AND REGION LIKE @REGION AND PROVINCE LIKE @PROVINCE";

        static public string SEARCHSUPPLIERWITHREGIONANDPROVINCE = "SELECT * FROM SUPPLIERSTBL WHERE (SUPPLIER_ID LIKE @SEARCHVALUE OR SUPPLIER_NAME LIKE @SEARCHVALUE) " +
            "AND REGION LIKE @REGION AND PROVINCE LIKE @PROVINCE";

        static public string SEARCHSUPPLIERWITHREGIONPROVINCEANDCITY = "SELECT * FROM SUPPLIERSTBL WHERE (SUPPLIER_ID LIKE @SEARCHVALUE OR SUPPLIER_NAME LIKE @SEARCHVALUE) AND REGION LIKE @REGION" +
            " AND PROVINCE LIKE @PROVINCE AND CITY LIKE @CITY";

        /*static public string SEARCHSUPPLIERWITHREGIONANDCITY = "SELECT * FROM SUPPLIERSTBL WHERE (SUPPLIER_ID LIKE @SEARCHVALUE OR SUPPLIER_NAME LIKE @SEARCHVALUE) AND REGION LIKE @REGION " +
            "AND CITY LIKE @CITY";*/

    }
}
