using GManagerial;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

static class AttachmentQuery
{
    //ATTACHMENT
    public const string INSERT_ATTACHMENT = "INSERT INTO ATTACHMENTSTBL (FILENAME, PATH, IMAGE, FILEDATA) VALUES (@FILENAME, @PATH, @IMAGE, @FILEDATA); SELECT SCOPE_IDENTITY();";
    public const string DELETE_ATTACHMENT = "DELETE FROM ATTACHMENTSTBL WHERE ID_ATTACHMENT = @ID_ATTACHMENT";

    //PRODUCT
    public const string INSERT_PRODUCT = "INSERT INTO PRODUCT_ATTACHMENT (FK_PRODUCT, FK_ATTACHMENT) VALUES (@FK_OBJECT, @FK_ATTACHMENT)";
    public const string SELECT_PRODUCT = "SELECT ATT.ID_ATTACHMENT, ATT.IMAGE, ATT.FILENAME, ATT.PATH, ATT.FILEDATA FROM ATTACHMENTSTBL ATT JOIN PRODUCT_ATTACHMENT PROD ON ATT.ID_ATTACHMENT = PROD.FK_ATTACHMENT " +
        "WHERE PROD.FK_PRODUCT = @FK_OBJECT";
    public const string DELETE_PRODUCT = "DELETE FROM PRODUCT_ATTACHMENT WHERE FK_ATTACHMENT = @FK_ATTACHMENT AND FK_PRODUCT = @FK_OBJECT";


    //CUSTOMER
    public const string INSERT_CUSTOMER = "INSERT INTO CUSTOMER_ATTACHMENT (FK_CUSTOMER, FK_ATTACHMENT) VALUES (@FK_OBJECT, @FK_ATTACHMENT)";
    public const string SELECT_CUSTOMER = "SELECT ATT.ID_ATTACHMENT, ATT.IMAGE, ATT.FILENAME, ATT.PATH FROM ATTACHMENTSTBL ATT JOIN CUSTOMER_ATTACHMENT CUST ON ATT.ID_ATTACHMENT = CUST.FK_ATTACHMENT " +
        "WHERE CUST.FK_CUSTOMER = @FK_OBJECT";
    public const string DELETE_CUSTOMER = "DELETE FROM CUSTOMER_ATTACHMENT WHERE FK_ATTACHMENT = @FK_ATTACHMENT AND FK_CUSTOMER = @FK_OBJECT";

    //SUPPLIER
    public const string INSERT_SUPPLIER = "INSERT INTO SUPPLIER_ATTACHMENT (FK_SUPPLIER, FK_ATTACHMENT) VALUES (@FK_OBJECT, @FK_ATTACHMENT)";
    public const string SELECT_SUPPLIER = "SELECT ATT.ID_ATTACHMENT, ATT.IMAGE, ATT.FILENAME, ATT.PATH FROM ATTACHMENTSTBL ATT JOIN SUPPLIER_ATTACHMENT SUPP " +
        "ON ATT.ID_ATTACHMENT = SUPP.FK_ATTACHMENT WHERE SUPP.FK_SUPPLIER = @FK_OBJECT";
    public const string DELETE_SUPPLIER = "DELETE FROM SUPPLIER_ATTACHMENT WHERE FK_ATTACHMENT = @FK_ATTACHMENT AND FK_SUPPLIER = @FK_OBJECT";

    //WAREHOUSEMOVEMENT
    public const string INSERT_WH_MOVEMENT = "INSERT INTO WAREHOUSE_MOVEMENT_ATTACHMENTS (FK_MOVEMENT, FK_ATTACHMENT) VALUES (@FK_OBJECT, @FK_ATTACHMENT)";
    public const string SELECT_WH_MOVEMENT = "SELECT ATT.ID_ATTACHMENT, ATT.IMAGE, ATT.FILENAME, ATT.PATH, ATT.FILEDATA FROM ATTACHMENTSTBL ATT JOIN WAREHOUSE_MOVEMENT_ATTACHMENTS WHM " +
        "ON ATT.ID_ATTACHMENT = WHM.FK_ATTACHMENT WHERE WHM.FK_MOVEMENT = @FK_OBJECT";
    public const string DELETE_WH_MOVEMENT = "DELETE FROM WAREHOUSE_MOVEMENT_ATTACHMENTS WHERE FK_ATTACHMENT = @FK_ATTACHMENT AND FK_MOVEMENT = @FK_OBJECT";
}



